---
title: "hmds: An R Package for Heuristic High and Multi Dimensional Scaling"
subtitle: 'A Vignette'
author: |
  | Masashi Okada
  | Okada Algorithm Private Invention Research Laboratory
  | okadaalgorithm@gmail.com
date: "hmds version 1.0 `r Sys.Date()`"
output: rmarkdown::pdf_document
bibliography: citation.bib
vignette: >
  %\VignetteIndexEntry{How to use package hmds}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
## Abstract
In this paper, we propose a heuristic in order to calculate the coordinates in high dimensions. If similarities or distances between two points and dimensions in the space are given, this heuristic calculates approximate coordinates in high dimensions. And if the similarities or distances have a contradict in metric space, the method calculates approximate coordinates. Its coordinates are available for lots of analysis. This heuristic proposed by R package.

## Introduction
Multi-Dimensional Scaling(MDS)[@Borg2005] is a statistical method in order to put points at coordinates. If the similarities or distances between the two points are given, MDS can put the data into two or three dimensional coordinate space. In this package, I proposed a heuristic in order to calculate coordinates in high dimensional space from the data of similarities or distances between two points. This heuristic calculates approximate coordinates in the dimensions given by user. And if the similarities or distances have a contradict in metric space, the method calculates approximate coordinates. And several important methods like Clustering[@Liu2007], Nearest Neighbor Search[@Zezula2006] and Data Visualization[@Ben2007] require coordinates in high dimensions as coordinate space. And this heuristic acts as follows. First of all, this program randomly puts the points in the high dimensional space. Its dimensions  are given by user. Then distances between two points compare with the given data in turns. If distances are longer than the data, the distances is made shorter by moving coordinates. If distance is shorter than the data, the distance is made longer. This iteration continues until the sum of distances becomes smaller than approximate rate or a limit of iteration. As a result, an approximate coordinate points in all data are acquired.

## Installation

```
> install.packages("hmds")
```

If download from GitHub you can use devtools by the commands:

```
> library(devtools)
> install_github("jirotubuyaki/hmds")

```

Once the packages are installed, it needs to be made accessible to the current R session by the commands:

```
> library(hmds)
```

For online help facilities or the details of a particular command (such as the function hmds) you can type:

```
> help(package="hmds")
```

##Method
This pakage has only one method. And it is excused by:

```
> output <- hmds(data = input, dim=20, approx=1.2, itera=10000)
```

Let's args be

* data is a numeric symmetric matrix of input data. it describe the distance between two points.
* dim describe dimensions of distance space between two points.
* approx is approximate rate of difference between input distance and output distanced. If the difference between input and output are shorter than approximate rate, iterations are halt.
* itera is iteration numbers to move coordinate space between all each two points.

Then let's return be

* output is a numeric matrix of points in a coordinate space. row is items. col is dimensions.

##Data
This package includes a sample dataset. The dataset containing a matrix of similarity between two points. The dataset is generated by R. Please check the data like this:

```
> data(package="hmds")
```

##Conclusions
The heuristic for Multi dimensional Scaling is described and explain how to use. This package can produce the approximate coordinates in high dimensions. And several improvements are planed. Please send suggestion and report bugs to okadaalgorithm@gmail.com.

##References
