// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hmds
NumericMatrix hmds(const NumericMatrix data, const int dim, const double approx, const int itera);
RcppExport SEXP hmds_hmds(SEXP dataSEXP, SEXP dimSEXP, SEXP approxSEXP, SEXP iteraSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const int >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const double >::type approx(approxSEXP);
    Rcpp::traits::input_parameter< const int >::type itera(iteraSEXP);
    rcpp_result_gen = Rcpp::wrap(hmds(data, dim, approx, itera));
    return rcpp_result_gen;
END_RCPP
}
