# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calcurate approximate positions in high dimensions
#' @param data NumericMatrix of input data. it describe the distance between two points.
#' @param dim int: it describe dimentions of distance space between two poitns.
#' @param approx double: A limit of distance of all pairs points in the space.  
#' @param itera int: iteration numbers to search space between two points.
#' @return Numeric Matrix of points in a distance space. row is items. col is dimentions.
#' @examples output <- hmds(matrix(1:9, nrow=3, ncol=3),dim=20,approx=1.2,itera=10000);
#' @export
#'
hmds <- function(data, dim = 50L, approx = 1.01, itera = 1000L) {
    .Call('hmds_hmds', PACKAGE = 'hmds', data, dim, approx, itera)
}

